name: Development Environment

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build integrated frontend
        uses: ./.github/actions/build-frontend

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build application
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          VERSION_SHA="${{ github.sha }}"
          go build -ldflags "-s -w -extldflags=-Wl,--strip-all -X github.com/komari-monitor/komari/utils.CurrentVersion=dev -X github.com/komari-monitor/komari/utils.VersionHash=${VERSION_SHA}" -o komari .

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: komari
          path: komari
